### ISSUE TITLE
error: failed to get `svg2pts` as a dependency of package `fourier-svg v0.1.0

### ISSUE THREAD

**Issue by davehorner** [vvcaw/fourier-svg#1]
just giving this a go win64.  looks like svg2pts
```
# cargo run --release -- -f fourier.svg
    Updating crates.io index
error: failed to get `svg2pts` as a dependency of package `fourier-svg v0.1.0 (C:\working\fourier-svg)`

Caused by:
  failed to load source for dependency `svg2pts`

Caused by:
  Unable to update C:\working\fourier-svg\lib\svg2pts

Caused by:
  failed to read `C:\working\fourier-svg\lib\svg2pts\Cargo.toml`

Caused by:
  The system cannot find the file specified. (os error 2)
```

I see https://github.com/exrok/svg2pts.  Just wanted to report the issue.
cargo install svg2pts
```
   Compiling svg2pts v0.1.5
error[E0425]: cannot find function `stdout` in this scope
   --> C:\Users\dhorner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\svg2pts-0.1.5\src\main.rs:256:5
    |
256 |     stdout() //sucks to be you
    |     ^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   + use crate::io::stdout;
    |
1   + use std::io::stdout;
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `svg2pts` (bin "svg2pts") due to previous error
error: failed to compile `svg2pts v0.1.5`, intermediate artifacts can be found at `C:\Users\dhorner\AppData\Local\Temp\cargo-installrI9KaD`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
that's a comment.

**Comment by vvcaw** [comment]
Hi, are you sure you cloned using this command: `git clone https://github.com/vvcaw/fourier-svg.git --recursive`? Especially using the `--recursive` flag? This makes sure that all submodules get cloned as well, this project has `vvcaw/svg2pts` as a git submodule in `lib` as I needed my own version of `svg2pts`. To fix this, you can either use this command: `git submodule update --init --recursive` in the cloned project root or just re-clone the repo with the `--recursive` flag, hope this helps!

**Comment by davehorner** [comment]
I did gloss over the --recursive.  What a strange easter egg.  I'd like to understand it more.  Does it do that for you when you don't do a recursive?  I guess that occurred when I did a cargo install.  It's also off subject...what caused the need for a fork?

I loaded `fourier-svg` up and it draws beautifully with the supplied fourier.svg.

I downloaded a tile from [christianp/aperiodic-monotile](https://github.com/christianp/aperiodic-monotile).
```sh
curl https://raw.githubusercontent.com/christianp/aperiodic-monotile/main/hat-monotile.svg -O
```
spin the tires.
```
cargo run --release -- -f hat-monotile.svg
```
The application comes up and does not display any points, lines, or circles.  It's empty background.

Let me know if you see anything wrong with the svg.  Thanks for a great video.  I will trace through some more and let you know what I find.

**Comment by davehorner** [comment]
```
start:
{x:0, y:0}
current:
{x:0, y:0}
last:
{x:0, y:0}
accuracy:
0.20000000000000001
target_dist:
5
pts:
(1) vec![{...}]
height:
4.5999999999999996
```
1 point and 4.5 height.  The svg is not a good candidate.  Regardless, thanks for the code and video.
